export const AI_LIBRARY_MAX_SAMPLES = 10_000;
export const AI_LIBRARY_DEFAULT_MAX_SAMPLES = 10_000;
export const AI_LIBRARY_DEFAULT_SEEDED_MAX_SAMPLES = 8_000;
export const AI_LIBRARY_DEFAULT_RECENT_WINDOW_TRADES = AI_LIBRARY_MAX_SAMPLES;
export const AI_LIBRARY_DEFAULT_EXTREME_TRADE_COUNT = AI_LIBRARY_MAX_SAMPLES;
export const AI_LIBRARY_LEGACY_RECENT_WINDOW_TRADES = 1_500;
export const AI_LIBRARY_LEGACY_EXTREME_TRADE_COUNT = 500;
export const AI_LIBRARY_MAX_ELIGIBLE_TRADE_WINDOW = 500_000;
